#!/usr/bin/env bash
#
# backup_seekers.sh — pull a consistent snapshot of the production seekers.db
# off the Railway volume and keep it here, on a machine Railway does not control.
#
# WHY THIS EXISTS
# ---------------
# Railway's own scheduled volume backups are a **Pro-plan** feature ($20/mo); this
# project is on Hobby. Meanwhile seekers.db is the one file in the whole system
# with no second copy anywhere: jobs.db can always be regenerated by re-running
# the local pipeline, but a lost Seeker account is simply lost. Decision 08 in
# docs/PLAN_ACCOUNTS.md requires backups before launch, so this is how that
# requirement is met without the plan upgrade.
#
# WHY NOT JUST DOWNLOAD THE FILE
# ------------------------------
# seekers.db runs in WAL mode. Copying the .db alone loses every transaction
# still sitting in the -wal file, and copying .db and -wal separately while the
# service is writing can capture the two at different instants — which yields a
# file that opens fine and is subtly wrong, the worst possible failure for a
# backup. So the snapshot is taken SERVER-SIDE with SQLite's online backup API
# (Connection.backup()), which is safe against concurrent writers by design, and
# only the resulting single self-consistent file is downloaded.
#
# USAGE
#   bash scripts/backup_seekers.sh              # snapshot -> data/backups/seekers/
#   RETAIN_DAYS=30 bash scripts/backup_seekers.sh
#
# Add to the daily cron next to daily_run.sh once accounts are deployed.

set -euo pipefail

SERVICE="${SERVICE:-backend}"
VOLUME="${VOLUME:-backend-volume}"
REMOTE_DB="${REMOTE_DB:-/data/seekers.db}"
# Deliberately dot-prefixed and fixed-name: a crash between snapshot and cleanup
# leaves exactly one stale file, which the next run overwrites, rather than
# accumulating copies on a volume that is already the tightest resource here.
REMOTE_SNAPSHOT="/data/.seekers-snapshot.db"
# Volume paths are relative to the mount: "/x" here is "/data/x" in the container.
REMOTE_SNAPSHOT_VOL="/.seekers-snapshot.db"
REMOTE_PY="/.seekers-snapshot.py"
DEST_DIR="${DEST_DIR:-$(cd "$(dirname "$0")/.." && pwd)/data/backups/seekers}"
RETAIN_DAYS="${RETAIN_DAYS:-30}"

STAMP="$(date -u +%Y%m%d_%H%M%S)"
DEST="$DEST_DIR/seekers-$STAMP.db"

log() { echo "[$(date -u '+%Y-%m-%d %H:%M:%S')] $*"; }

mkdir -p "$DEST_DIR"

log "Snapshotting $REMOTE_DB on service '$SERVICE' (online backup API)…"
# python3 is guaranteed present: the service *is* a Python app. sqlite3 is stdlib.
# The snapshot is written next to the source so it lands on the same volume and
# no data crosses the network un-snapshotted.
#
# The snapshot code is UPLOADED and then run by path, rather than passed inline.
# `railway ssh` joins its COMMAND argv into one string and runs it through
# `bash -c` on the far side, so local quoting is consumed before it ever arrives:
# a heredoc arrives as separate shell words ("import: command not found"), and
# even a quoted one-liner arrives with bare parentheses ("syntax error near
# unexpected token `('"). Uploading means the remote command is
# `python3 /data/.seekers-snapshot.py` — no quotes, no spaces in arguments, no
# metacharacters, nothing left for a shell to reinterpret.
read -r -d '' SNAPSHOT_PY <<PY || true
import os, sqlite3, sys
src_path, dst_path = '$REMOTE_DB', '$REMOTE_SNAPSHOT'
if not os.path.exists(src_path):
    sys.exit('seekers.db does not exist yet at ' + src_path + ' - nothing to back up')
if os.path.exists(dst_path):
    os.remove(dst_path)
src = sqlite3.connect('file:' + src_path + '?mode=ro', uri=True)
dst = sqlite3.connect(dst_path)
with dst:
    src.backup(dst)
dst.close(); src.close()
print('snapshot bytes:', os.path.getsize(dst_path))
PY
LOCAL_PY="$(mktemp -t seekers-snapshot).py"
printf '%s\n' "$SNAPSHOT_PY" > "$LOCAL_PY"
cleanup() {
    rm -f "$LOCAL_PY"
    # Runs on EVERY exit path, including the early 'nothing to back up' one —
    # otherwise the next run's upload fails on a file this run left behind.
    }
trap cleanup EXIT
railway volume files -v "$VOLUME" upload --overwrite "$LOCAL_PY" "$REMOTE_PY" >/dev/null

# `railway ssh` does not reliably propagate the remote exit status, so the remote
# outcome is read from its output rather than from $?.
SNAPSHOT_OUT="$(railway ssh -s "$SERVICE" python3 "/data${REMOTE_PY}" 2>&1 || true)"
echo "$SNAPSHOT_OUT" | grep -v 'Using SSH key' || true

# Before accounts are deployed there is genuinely nothing to back up. That is a
# normal state, not a failure — exit 0 so a cron entry added early does not mail
# a failure every night until the first deploy.
if echo "$SNAPSHOT_OUT" | grep -q 'nothing to back up'; then
    log "No seekers.db in production yet — nothing to do."
    exit 0
fi
if ! echo "$SNAPSHOT_OUT" | grep -q 'snapshot bytes:'; then
    log "ERROR: snapshot did not complete. Remote output above."
    exit 1
fi

log "Downloading snapshot…"
railway volume files -v "$VOLUME" download "$REMOTE_SNAPSHOT_VOL" "$DEST"

# Remove the copy from the volume whether or not the download succeeded cleanly —
# leaving a second credential store lying around on shared storage is exactly the
# risk this script is supposed to reduce, not add to.
log "Removing snapshot from the volume…"
railway volume files -v "$VOLUME" delete "$REMOTE_SNAPSHOT_VOL" || \
    log "WARNING: could not delete $REMOTE_SNAPSHOT — remove it manually"

# Prove the download is a usable database rather than a truncated file. A backup
# you have never opened is a hope, not a backup.
log "Verifying…"
python3 - "$DEST" <<'PY'
import sqlite3, sys
path = sys.argv[1]
conn = sqlite3.connect(path)
if conn.execute("PRAGMA integrity_check").fetchone()[0] != "ok":
    sys.exit("FAILED: integrity_check did not return ok")
n = conn.execute("SELECT COUNT(*) FROM seekers").fetchone()[0]
conn.close()
print(f"  integrity ok — {n} Seeker(s) in this snapshot")
PY

# Retention. Unlike backup.py (which keeps every jobs.db snapshot forever because
# each one is a dated record of the market), these hold personal data, so keeping
# them indefinitely is a PDPO retention problem we would be creating ourselves.
if [ "$RETAIN_DAYS" -gt 0 ]; then
    find "$DEST_DIR" -name 'seekers-*.db' -type f -mtime +"$RETAIN_DAYS" -print -delete \
        | sed 's/^/  pruned: /' || true
fi

log "Done — $DEST"
log "Kept $(find "$DEST_DIR" -name 'seekers-*.db' -type f | wc -l | tr -d ' ') snapshot(s), retention ${RETAIN_DAYS}d"
